### ISSUE TITLE
Inconsistent space around headings

### ISSUE THREAD

**Issue by michaellenaghan** [typlog/yue.css#19]
I think there's an issue here:

https://github.com/typlog/yue.css/blob/76f4cca3898c206fd2e0fcda7431ffecc959046e/src/yue.css#L29-L30

Note the progression of top and bottom margins:

```css
.yue h2 {
  ...
  margin-top: 1.42em;
  margin-bottom: 0.4em;
}

.yue h3 {
  ...
  margin-top: 1.62em;
  margin-bottom: 1em;
}

.yue h4,
.yue h5,
.yue h6 {
  ...
  margin-top: 1.4em;
  margin-bottom: 0.8em;
}
```

`h3`s margins are larger than both `h2`s and `h4`/`h5`/`h6`s.
